import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";
import { Navbar } from "@/components/navbar";

;

const myFont = localFont({ src: "../font/fontOne.otf" });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className}  antialiased md:mx-32 mx-5`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
